-- TODO: add a shell script to auto install everything. Or use Makefile
-- require("alvin.plugins")
require("alvin.plugins-lazy")
require("alvin.options")
require("alvin.keymaps")
require("alvin.colorscheme")
require("alvin.cmp")
require("alvin.lsp")
require("alvin.nvim-tree")
require("alvin.treesitter")
require("alvin.autopairs")
require("alvin.comment")
require("alvin.gitsigns")
require("alvin.lualine")
require("alvin.autocommands")
require("alvin.whichkey")
require("alvin.indentline")
require("alvin.trouble")
require("alvin.todo-comments")
require("alvin.lspsaga")
require("alvin.colorizer")
require("alvin.telescope-config")
